import requests
from bs4 import BeautifulSoup
import json

# List of URLs to scrape
urls = [

"https://chennai.vit.ac.in/member/dr-ganesan-r/",
"https://chennai.vit.ac.in/member/dr-geetha-s/",
"https://chennai.vit.ac.in/member/dr-parvathi-r/",
"https://chennai.vit.ac.in/member/dr-janaki-meena-m/",
"https://chennai.vit.ac.in/member/dr-jeganathan-l/",
"https://chennai.vit.ac.in/member/dr-maheswari-n/",
"https://chennai.vit.ac.in/member/dr-manjula-d/",
"https://chennai.vit.ac.in/member/dr-nagaraj-s-v/",
"https://chennai.vit.ac.in/member/dr-nayeemulla-khan-a/",
"https://chennai.vit.ac.in/member/dr-nithyanandam-p/",
"https://chennai.vit.ac.in/member/dr-pattabiraman-v/",
"https://chennai.vit.ac.in/member/dr-subbulakshmi-t/",
"https://chennai.vit.ac.in/member/dr-syed-ibrahim-s-p/",
"https://chennai.vit.ac.in/member/dr-viswanathan-v/",
"https://chennai.vit.ac.in/member/dr-bharadwaja-kumar-g/",
"https://chennai.vit.ac.in/member/dr-jenila-livingston-l-m/",
"https://chennai.vit.ac.in/member/dr-malathi-g/",
"https://chennai.vit.ac.in/member/dr-neela-narayanan-v/",
"https://chennai.vit.ac.in/member/dr-pradeep-kumar-t-s/",
"https://chennai.vit.ac.in/member/dr-priyadarshini-j/",
"https://chennai.vit.ac.in/member/dr-renta-chintala-bhargavi/",
"https://chennai.vit.ac.in/member/dr-saleena-b/",
"https://chennai.vit.ac.in/member/dr-santhi-v/",
"https://chennai.vit.ac.in/member/dr-sathis-kumar-b/",
"https://chennai.vit.ac.in/member/dr-sivabalakrishnan-m/",
"https://chennai.vit.ac.in/member/dr-anand-m/",
"https://chennai.vit.ac.in/member/dr-anusha-k/",
"https://chennai.vit.ac.in/member/dr-asnath-victy-phamila-y/",
"https://chennai.vit.ac.in/member/dr-b-v-a-n-s-s-prabhakar-rao/",
"https://chennai.vit.ac.in/member/dr-christopher-columbus-c/",
"https://chennai.vit.ac.in/member/dr-dinakaran-m/",
"https://chennai.vit.ac.in/member/dr-harini-s/",
"https://chennai.vit.ac.in/member/dr-jaisakthi-s-m/",
"https://chennai.vit.ac.in/member/dr-jeya-mala-d/",
"https://chennai.vit.ac.in/member/dr-karmel-a/",
"https://chennai.vit.ac.in/member/dr-kumar-r/",
"https://chennai.vit.ac.in/member/dr-nithya-darisini-p-s/",
"https://chennai.vit.ac.in/member/dr-parvathy-a-k/",
"https://chennai.vit.ac.in/member/dr-prassanna-j/",
"https://chennai.vit.ac.in/member/dr-rajalakshmi-r/",
"https://chennai.vit.ac.in/member/dr-rekha-d/",
"https://chennai.vit.ac.in/member/dr-renuka-devi-s/",
"https://chennai.vit.ac.in/member/dr-rukmani-p/",
"https://chennai.vit.ac.in/member/dr-sandhya-m/",
"https://chennai.vit.ac.in/member/dr-sandhya-p/",
"https://chennai.vit.ac.in/member/dr-shridevi-s/",
"https://chennai.vit.ac.in/member/dr-sivagami-m/",
"https://chennai.vit.ac.in/member/dr-suganya-g/",
"https://chennai.vit.ac.in/member/dr-surya-prakash-tiwari/",
"https://chennai.vit.ac.in/member/dr-sweetlin-hemalatha-c/",
"https://chennai.vit.ac.in/member/dr-umamaheswari-e/",
"https://chennai.vit.ac.in/member/dr-appalaraju-muralidhar/",
"https://chennai.vit.ac.in/member/dr-dhanalakshmi-r/",
"https://chennai.vit.ac.in/member/dr-ganala-santoshi/",
"https://chennai.vit.ac.in/member/dr-ganesh-n/",
"https://chennai.vit.ac.in/member/dr-graceline-jasmine-s/",
"https://chennai.vit.ac.in/member/dr-janani-t/",
"https://chennai.vit.ac.in/member/dr-kanchana-devi-v/",
"https://chennai.vit.ac.in/member/dr-manjula-v/",
"https://chennai.vit.ac.in/member/dr-nachiyappan-s/",
"https://chennai.vit.ac.in/member/dr-padmavathy-t-v/",
"https://chennai.vit.ac.in/member/dr-prakash-p/",
"https://chennai.vit.ac.in/member/dr-premalatha-m/",
"https://chennai.vit.ac.in/member/dr-priyaadharshini-m/",
"https://chennai.vit.ac.in/member/dr-rabindra-kumar-singh/",
"https://chennai.vit.ac.in/member/dr-radha-r/",
"https://chennai.vit.ac.in/member/dr-rama-parvathy-l/",
"https://chennai.vit.ac.in/member/dr-sajidha-s-a/",
"https://chennai.vit.ac.in/member/dr-shyamala-l/",
"https://chennai.vit.ac.in/member/dr-srinivasa-perumal-r/",
"https://chennai.vit.ac.in/member/dr-suganya-r/",
"https://chennai.vit.ac.in/member/dr-thanikachalam-v/",
"https://chennai.vit.ac.in/member/dr-thomas-abraham-j-v/",
"https://chennai.vit.ac.in/member/dr-tulasi-prasad-sariki/",
"https://chennai.vit.ac.in/member/dr-vergin-raja-sarobin-m/",
"https://chennai.vit.ac.in/member/dr-abdul-quadir-md/",
"https://chennai.vit.ac.in/member/dr-alok-chauhan/",
"https://chennai.vit.ac.in/member/dr-anita-x/",
"https://chennai.vit.ac.in/member/dr-arthi-m/",
"https://chennai.vit.ac.in/member/dr-bharathi-raja-s/",
"https://chennai.vit.ac.in/member/dr-bhavadharini-r-m/",
"https://chennai.vit.ac.in/member/dr-christy-jackson-j/",
"https://chennai.vit.ac.in/member/dr-elango-n-m/",
"https://chennai.vit.ac.in/member/dr-jani-anbarasi-l/",
"https://chennai.vit.ac.in/member/dr-jayanthi-r/",
"https://chennai.vit.ac.in/member/dr-jayasudha-m/",
"https://chennai.vit.ac.in/member/dr-maheswari-s/",
"https://chennai.vit.ac.in/member/dr-maria-anu-v/",
"https://chennai.vit.ac.in/member/dr-menaka-pushpa-a/",
"https://chennai.vit.ac.in/member/dr-nisha-v-m/",
"https://chennai.vit.ac.in/member/dr-punitha-k/",
"https://chennai.vit.ac.in/member/dr-rajesh-kumar/",
"https://chennai.vit.ac.in/member/dr-rajesh-m/",
"https://chennai.vit.ac.in/member/dr-rajkumar-s/",
"https://chennai.vit.ac.in/member/dr-rama-prabha-k-p/",
"https://chennai.vit.ac.in/member/dr-rathna-r/",
"https://chennai.vit.ac.in/member/dr-saravanan-p/",
"https://chennai.vit.ac.in/member/dr-shola-usha-rani/",
"https://chennai.vit.ac.in/member/dr-sivakami-r/",
"https://chennai.vit.ac.in/member/dr-sridhar-r/",
"https://chennai.vit.ac.in/member/dr-vallidevi-k/",
"https://chennai.vit.ac.in/member/dr-venkatraman-s/",
"https://chennai.vit.ac.in/member/dr-vijayalakshmi-a/",
"https://chennai.vit.ac.in/member/dr-anandan-p/",
"https://chennai.vit.ac.in/member/dr-anita-christaline-j/",
"https://chennai.vit.ac.in/member/dr-anusooya-g/",
"https://chennai.vit.ac.in/member/dr-asha-jerlin-m/",
"https://chennai.vit.ac.in/member/dr-ayesha-sk/",
"https://chennai.vit.ac.in/member/dr-balasundaram-a/",
"https://chennai.vit.ac.in/member/dr-braveen-m/",
"https://chennai.vit.ac.in/member/dr-gayathri-r/",
"https://chennai.vit.ac.in/member/dr-hema-n/",
"https://chennai.vit.ac.in/member/dr-ilakiyaselvan-n/",
"https://chennai.vit.ac.in/member/dr-jayaram-b/",
"https://chennai.vit.ac.in/member/dr-kanniga-devi-r/",
"https://chennai.vit.ac.in/member/dr-kavitha-d/",
"https://chennai.vit.ac.in/member/dr-lekshmi-k/",
"https://chennai.vit.ac.in/member/dr-leninisha-s/",
"https://chennai.vit.ac.in/member/dr-madheswari-k/",
"https://chennai.vit.ac.in/member/dr-malini-a/",
"https://chennai.vit.ac.in/member/dr-manas-ranjan-prusty/",
"https://chennai.vit.ac.in/member/dr-manimegalai-t/",
"https://chennai.vit.ac.in/member/dr-manju-g/",
"https://chennai.vit.ac.in/member/dr-muthumanikandan-v/",
"https://chennai.vit.ac.in/member/dr-palani-thanaraj-k/",
"https://chennai.vit.ac.in/member/dr-prabhakaran-r/",
"https://chennai.vit.ac.in/member/dr-pradeep-k-v/",
"https://chennai.vit.ac.in/member/dr-prakash-b/",
"https://chennai.vit.ac.in/member/dr-prasad-m/",
"https://chennai.vit.ac.in/member/dr-praveen-joe-i-r/",
"https://chennai.vit.ac.in/member/dr-priyadarshini-ramasubramanian/",
"https://chennai.vit.ac.in/member/dr-raja-m/",
"https://chennai.vit.ac.in/member/dr-rajakumar-r/",
"https://chennai.vit.ac.in/member/dr-rajarajeswari-s/",
"https://chennai.vit.ac.in/member/dr-renjith-p-n/",
"https://chennai.vit.ac.in/member/dr-renuka-devi-r/",
"https://chennai.vit.ac.in/member/dr-revathi-a-r/",
"https://chennai.vit.ac.in/member/dr-sakthivel-v/",
"https://chennai.vit.ac.in/member/dr-sambasiva-rao-kambala/",
"https://chennai.vit.ac.in/member/dr-sandeep-kumar-satapathy/",
"https://chennai.vit.ac.in/member/dr-sankar-p/",
"https://chennai.vit.ac.in/member/dr-saranyaraj-d/",
"https://chennai.vit.ac.in/member/dr-sathian-d/",
"https://chennai.vit.ac.in/member/dr-sathyarajasekaran-k/",
"https://chennai.vit.ac.in/member/dr-sellam-v/",
"https://chennai.vit.ac.in/member/dr-senthil-kumar-a-m/",
"https://chennai.vit.ac.in/member/dr-sheik-abdullah-a/",
"https://chennai.vit.ac.in/member/dr-sherly-a/",
"https://chennai.vit.ac.in/member/dr-sivakumar-p/",
"https://chennai.vit.ac.in/member/dr-sobitha-ahila-s/",
"https://chennai.vit.ac.in/member/dr-sridevi-s/",
"https://chennai.vit.ac.in/member/dr-subbulakshmi-p/",
"https://chennai.vit.ac.in/member/dr-suguna-m/",
"https://chennai.vit.ac.in/member/dr-sureshkumar-wi/",
"https://chennai.vit.ac.in/member/dr-uma-maheswari-j/",
"https://chennai.vit.ac.in/member/dr-umitty-srinivasa-rao/",
"https://chennai.vit.ac.in/member/dr-vijayakumar-k-p/",
"https://chennai.vit.ac.in/member/dr-yogesh-c/",
"https://chennai.vit.ac.in/member/dr-abinaya-s/",
"https://chennai.vit.ac.in/member/dr-abishi-chowdhury/",
"https://chennai.vit.ac.in/member/dr-amrit-pal/",
"https://chennai.vit.ac.in/member/dr-amutha-jeevakumari-s-a/",
"https://chennai.vit.ac.in/member/dr-amutha-s/",
"https://chennai.vit.ac.in/member/dr-anubha-pearline-s/",
"https://chennai.vit.ac.in/member/dr-arunkumar-v/",
"https://chennai.vit.ac.in/member/dr-ashoka-rajan-r/",
"https://chennai.vit.ac.in/member/dr-balasaraswathi-v-r/",
"https://chennai.vit.ac.in/member/dr-bhuvaneswari-a/",
"https://chennai.vit.ac.in/member/dr-bhuvaneswari-amma-n-g/",
"https://chennai.vit.ac.in/member/dr-devi-k/",
"https://chennai.vit.ac.in/member/dr-dhavakumar-p/",
"https://chennai.vit.ac.in/member/dr-dominic-savio-m/",
"https://chennai.vit.ac.in/member/dr-edward-jero-s/",
"https://chennai.vit.ac.in/member/dr-elakiya-e/",
"https://chennai.vit.ac.in/member/dr-gayathri-devi-s/",
"https://chennai.vit.ac.in/member/dr-ilavarasi-a-k/",
"https://chennai.vit.ac.in/member/dr-indira-b/",
"https://chennai.vit.ac.in/member/dr-joshua-sunder-david-reddipogu/",
"https://chennai.vit.ac.in/member/dr-jothi-r/",
"https://chennai.vit.ac.in/member/dr-kabilan-k/",
"https://chennai.vit.ac.in/member/dr-kaja-mohideen-a/",
"https://chennai.vit.ac.in/member/dr-kalaipriyan-t/",
"https://chennai.vit.ac.in/member/dr-kavitha-j-c/",
"https://chennai.vit.ac.in/member/dr-krithiga-r/",
"https://chennai.vit.ac.in/member/dr-lakshmi-harika-palivela/",
"https://chennai.vit.ac.in/member/dr-linda-joseph/",
"https://chennai.vit.ac.in/member/dr-malini-deepika-m/",
"https://chennai.vit.ac.in/member/dr-mansoor-hussain-d/",
"https://chennai.vit.ac.in/member/dr-mercy-rajaselvi-beaulah-p/",
"https://chennai.vit.ac.in/member/dr-muthukumaran-k/",
"https://chennai.vit.ac.in/member/dr-om-kumar-c-u/",
"https://chennai.vit.ac.in/member/dr-padmanaban-r/",
"https://chennai.vit.ac.in/member/dr-pandiyaraju-v/",
"https://chennai.vit.ac.in/member/dr-parkavi-k/",
"https://chennai.vit.ac.in/member/dr-pavithra-l-k/",
"https://chennai.vit.ac.in/member/dr-pavithra-s/",
"https://chennai.vit.ac.in/member/dr-pradeep-k/",
"https://chennai.vit.ac.in/member/dr-radhika-selvamani-b/",
"https://chennai.vit.ac.in/member/dr-raja-sree-t/",
"https://chennai.vit.ac.in/member/dr-rajakumar-arul/",
"https://chennai.vit.ac.in/member/dr-rajiv-vincent/",
"https://chennai.vit.ac.in/member/dr-rishikeshan-c-a/",
"https://chennai.vit.ac.in/member/dr-sambath-m/",
"https://chennai.vit.ac.in/member/dr-sandosh-s/",
"https://chennai.vit.ac.in/member/dr-sangeetha-n/",
"https://chennai.vit.ac.in/member/dr-saraswathi-d/",
"https://chennai.vit.ac.in/member/dr-shivani-gupta/",
"https://chennai.vit.ac.in/member/dr-shruti-mishra/",
"https://chennai.vit.ac.in/member/dr-sivaramakrishnan-n/",
"https://chennai.vit.ac.in/member/dr-srisakthi-saravanan/",
"https://chennai.vit.ac.in/member/dr-subitha-d/",
"https://chennai.vit.ac.in/member/dr-sudha-a/",
"https://chennai.vit.ac.in/member/dr-suganeshwari-g/",
"https://chennai.vit.ac.in/member/dr-suseela-s/",
"https://chennai.vit.ac.in/member/dr-swaminathan-a/",
"https://chennai.vit.ac.in/member/dr-tamilarasi-k/",
"https://chennai.vit.ac.in/member/dr-trilok-nath-pandey/",
"https://chennai.vit.ac.in/member/dr-vidhya-lakshmi-m/",
"https://chennai.vit.ac.in/member/dr-vignesh-u/",
"https://chennai.vit.ac.in/member/dr-abirami-s/",
"https://chennai.vit.ac.in/member/dr-afruza-begum/",
"https://chennai.vit.ac.in/member/dr-ahadit-a-b/",
"https://chennai.vit.ac.in/member/dr-ancy-micheal-a/",
"https://chennai.vit.ac.in/member/dr-aravindkumar-s/",
"https://chennai.vit.ac.in/member/dr-aswiga-r-v/",
"https://chennai.vit.ac.in/member/dr-avuthu-avinash-reddy/",
"https://chennai.vit.ac.in/member/dr-balraj-e-2/",
"https://chennai.vit.ac.in/member/dr-benil-t/",
"https://chennai.vit.ac.in/member/dr-benila-s/",
"https://chennai.vit.ac.in/member/dr-brindha-s/",
"https://chennai.vit.ac.in/member/dr-brindha-v/",
"https://chennai.vit.ac.in/member/dr-deepa-nivethika-s/",
"https://chennai.vit.ac.in/member/dr-deepika-roselind-j/",
"https://chennai.vit.ac.in/member/dr-ilavendhan-a/",
"https://chennai.vit.ac.in/member/dr-indra-priyadharshini-s/",
"https://chennai.vit.ac.in/member/dr-jannath-nisha-o-s/",
"https://chennai.vit.ac.in/member/dr-jeipratha-p-n/",
"https://chennai.vit.ac.in/member/dr-joe-dhanith-p-r/",
"https://chennai.vit.ac.in/member/dr-johnsi-r/",
"https://chennai.vit.ac.in/member/dr-joshan-athanesious-j/",
"https://chennai.vit.ac.in/member/dr-kanimozhi-s/",
"https://chennai.vit.ac.in/member/dr-kanthimathi-s/",
"https://chennai.vit.ac.in/member/dr-karthika-s-k/",
"https://chennai.vit.ac.in/member/dr-karthikeyan-n/",
"https://chennai.vit.ac.in/member/dr-kavipriya-g/",
"https://chennai.vit.ac.in/member/dr-kaviya-elakkiya-m/",
"https://chennai.vit.ac.in/member/dr-kiruthika-s/",
"https://chennai.vit.ac.in/member/dr-kishor-kisan-ingle/",
"https://chennai.vit.ac.in/member/dr-kumaran-k/",
"https://chennai.vit.ac.in/member/dr-leki-chom-thungon/",
"https://chennai.vit.ac.in/member/dr-m-revathi/",
"https://chennai.vit.ac.in/member/dr-malathi-d/",
"https://chennai.vit.ac.in/member/dr-manikandan-p/",
"https://chennai.vit.ac.in/member/dr-marimuthu-m/",
"https://chennai.vit.ac.in/member/dr-mary-shamala-l/",
"https://chennai.vit.ac.in/member/dr-modigari-narendra/",
"https://chennai.vit.ac.in/member/dr-monica-k-m/",
"https://chennai.vit.ac.in/member/dr-nathezhtha-t/",
"https://chennai.vit.ac.in/member/dr-nivethitha-v/",
"https://chennai.vit.ac.in/member/dr-noel-jeygar-robert-v/",
"https://chennai.vit.ac.in/member/dr-omana-j/",
"https://chennai.vit.ac.in/member/dr-padma-j/",
"https://chennai.vit.ac.in/member/dr-poonkodi-m/",
"https://chennai.vit.ac.in/member/dr-prabha-b/",
"https://chennai.vit.ac.in/member/dr-pravin-renold-a/",
"https://chennai.vit.ac.in/member/dr-prem-sankar-n/",
"https://chennai.vit.ac.in/member/dr-premanand-v/",
"https://chennai.vit.ac.in/member/dr-rajesh-r/",
"https://chennai.vit.ac.in/member/dr-ranjith-kumar-m/",
"https://chennai.vit.ac.in/member/dr-reena-roy-r/",
"https://chennai.vit.ac.in/member/dr-rolla-subrahmanyam/",
"https://chennai.vit.ac.in/member/dr-sahaya-beni-prathiba-b/",
"https://chennai.vit.ac.in/member/dr-sakthivel-r/",
"https://chennai.vit.ac.in/member/dr-saranya-g/",
"https://chennai.vit.ac.in/member/dr-sendhil-r/",
"https://chennai.vit.ac.in/member/dr-senthil-prakash-p-n/",
"https://chennai.vit.ac.in/member/dr-sharmila-devi-s/",
"https://chennai.vit.ac.in/member/dr-siva-priya-m-s/",
"https://chennai.vit.ac.in/member/dr-sivaranjani-n/",
"https://chennai.vit.ac.in/member/dr-smrithy-g-s/",
"https://chennai.vit.ac.in/member/dr-sreeja-p-s/",
"https://chennai.vit.ac.in/member/dr-sudharson-s-2/",
"https://chennai.vit.ac.in/member/dr-sudheer-kumar-e/",
"https://chennai.vit.ac.in/member/dr-sujithra-kanmani-r/",
"https://chennai.vit.ac.in/member/dr-suvidha-rupesh-kumar/",
"https://chennai.vit.ac.in/member/dr-uma-maheswari-k/",
"https://chennai.vit.ac.in/member/dr-umesh-k/",
"https://chennai.vit.ac.in/member/dr-valarmathi-k/",
"https://chennai.vit.ac.in/member/dr-valarmathi-sudhakar/",
"https://chennai.vit.ac.in/member/dr-vatchala-s/",
"https://chennai.vit.ac.in/member/dr-vijayaprabakaran-k/",
"https://chennai.vit.ac.in/member/dr-vinothini-a/",
"https://chennai.vit.ac.in/member/dr-vivekanandan-m/",
"https://chennai.vit.ac.in/member/dr-selvam-d/",
"https://chennai.vit.ac.in/member/dr-jahangeer-sidiq-s/",
"https://chennai.vit.ac.in/member/dr-sarita-kumari/",
"https://chennai.vit.ac.in/member/dr-gayathri-r-2/",
"https://chennai.vit.ac.in/member/dr-helen-vijitha-p/",
"https://chennai.vit.ac.in/member/dr-kshma-trivedi/",
"https://chennai.vit.ac.in/member/dr-madura-meenakshi-r/",
"https://chennai.vit.ac.in/member/dr-tahir-mujtaba/",
"https://chennai.vit.ac.in/member/dr-tapabrata-roy/",
"https://chennai.vit.ac.in/member/prof-kavya-alluru/",
"https://chennai.vit.ac.in/member/prof-khadar-nawas-k/",
"https://chennai.vit.ac.in/member/prof-nivedita-m/",
"https://chennai.vit.ac.in/member/prof-hemalatha-k/",
"https://chennai.vit.ac.in/member/prof-jai-vinita-l/",
"https://chennai.vit.ac.in/member/prof-johanan-joysingh-s/",
"https://chennai.vit.ac.in/member/prof-karthika-v/",
"https://chennai.vit.ac.in/member/prof-logeswari-g/",
"https://chennai.vit.ac.in/member/prof-prethija-g/",
"https://chennai.vit.ac.in/member/prof-shree-prakash/",
"https://chennai.vit.ac.in/member/prof-sudha-c/",
"https://chennai.vit.ac.in/member/prof-angelin-beulah-s/",
"https://chennai.vit.ac.in/member/prof-balaji-v/",
"https://chennai.vit.ac.in/member/prof-berin-shalu-s/",
"https://chennai.vit.ac.in/member/prof-deepika-r/",
"https://chennai.vit.ac.in/member/prof-hemila-rexline-d/",
"https://chennai.vit.ac.in/member/prof-jeyamani-d/",
"https://chennai.vit.ac.in/member/prof-jeyavim-sherin-r-c/",
"https://chennai.vit.ac.in/member/prof-jeyavim-sherlin-r-c/",
"https://chennai.vit.ac.in/member/prof-johnsi-r/",
"https://chennai.vit.ac.in/member/prof-manoranjitham-m-2/",
"https://chennai.vit.ac.in/member/prof-pankaja-lakshmi-p/",
"https://chennai.vit.ac.in/member/prof-priyanka-mishra/",
"https://chennai.vit.ac.in/member/prof-rajathi-c/",
"https://chennai.vit.ac.in/member/prof-ramesh-kannan-r/",
"https://chennai.vit.ac.in/member/prof-safiya-parvin-a/",
"https://chennai.vit.ac.in/member/prof-sarah-prithvika-p-c/",
"https://chennai.vit.ac.in/member/prof-shahjahan-sofia-nishath/",
"https://chennai.vit.ac.in/member/prof-softya-sebastian/",
"https://chennai.vit.ac.in/member/prof-sukanya-g/",
"https://chennai.vit.ac.in/member/ms-anu-ragavi-v/",
"https://chennai.vit.ac.in/member/ms-julie-sharine/",
"https://chennai.vit.ac.in/member/ranjith-j/",
"https://chennai.vit.ac.in/member/sheela-lavanya-j-m/",
]

# Initialize an empty list to store scraped data
scraped_data = []

# Function to scrape name and image from a URL
def scrape_member_details(url):
    response = requests.get(url, verify=False)  # Disable SSL verification for this example
    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')

        # Find the name using the class 'item-title'
        name_tag = soup.find('h3', class_='item-title')  # Use h2 or adjust based on the structure
        name = name_tag.get_text(strip=True) if name_tag else 'No name found'

        # Find the image URL
        image_tag = soup.find('img', class_='wp-post-image')  # Adjust this based on actual structure
        image_url = image_tag['src'] if image_tag else 'No image found'

        # Return the scraped details as a dictionary
        return {
            'name': name,
            'image_url': image_url
        }
    else:
        print(f"Failed to retrieve {url}")
        return None

# Scrape each URL and collect the data
for url in urls:
    member_details = scrape_member_details(url)
    if member_details:
        scraped_data.append(member_details)

# Output the scraped data as JSON
with open('scraped_data.json', 'w') as json_file:
    json.dump(scraped_data, json_file, indent=4)

print("Data scraped successfully and saved to 'scraped_data.json'")
