-- Create ratings table for per-teacher 4-metric star ratings.
drop table if exists public.ratings;

create table if not exists public.ratings (
  id bigint generated by default as identity primary key,
  teacher_id uuid not null references public.teachers(id) on delete cascade,
  teaching_rating smallint not null check (teaching_rating between 1 and 5),
  generous_marking_rating smallint not null check (generous_marking_rating between 1 and 5),
  less_assignments_rating smallint not null check (less_assignments_rating between 1 and 5),
  human_rating smallint not null check (human_rating between 1 and 5),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists ratings_teacher_id_idx on public.ratings (teacher_id);
create index if not exists ratings_created_at_idx on public.ratings (created_at desc);

alter table public.ratings enable row level security;

-- Allow anyone to read ratings.
drop policy if exists "Allow public read ratings" on public.ratings;
create policy "Allow public read ratings"
on public.ratings
for select
to anon, authenticated
using (true);

-- Allow anyone to submit ratings (anonymous classroom feedback use case).
drop policy if exists "Allow public insert ratings" on public.ratings;
create policy "Allow public insert ratings"
on public.ratings
for insert
to anon, authenticated
with check (true);
